In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

C:\Users\krish\AppData\Local\Temp\ipykernel_5736\1865116140.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books['Image-URL-M'][1]

'http://images.amazon.com/images/P/0002005018.01.MZZZZZZZ.jpg'

In [5]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [7]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [8]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [9]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
books.duplicated().sum()

np.int64(0)

In [12]:
ratings.duplicated().sum()

np.int64(0)

In [13]:
users.duplicated().sum()

np.int64(0)

## Popularity Based Recommender System

In [14]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [15]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [16]:
# Only select the 'Book-Title' and 'Book-Rating' columns first
avg_rating_df = ratings_with_name[['Book-Title', 'Book-Rating']].groupby('Book-Title').mean(numeric_only=True).reset_index()

# Rename the column
avg_rating_df.rename(columns={'Book-Rating': 'avg_rating'}, inplace=True)

# Display the result
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [17]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [18]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)
popular_df

,Book-Title,num_ratings,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [19]:
print(books.columns)

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [20]:
# Normalize titles to match properly
popular_df['Book-Title'] = popular_df['Book-Title'].str.strip().str.lower()
books['Book-Title'] = books['Book-Title'].str.strip().str.lower()

# Merge
merged_df = popular_df.merge(books, on='Book-Title', how='left')

# Auto-detect real column names
columns = merged_df.columns.tolist()
author_col = next((col for col in columns if 'Book-Author' in col), None)
image_col = next((col for col in columns if 'Image-URL-M' in col), None)

# Final selection
popular_df_cleaned = merged_df.drop_duplicates('Book-Title')[
    ['Book-Title', author_col, image_col, 'num_ratings', 'avg_rating']
].rename(columns={
    author_col: 'Book-Author',
    image_col: 'Image-URL-M'
})

print(popular_df_cleaned.head())

                                           Book-Title    Book-Author  \
0   harry potter and the prisoner of azkaban (book 3)  J. K. Rowling
3        harry potter and the goblet of fire (book 4)  J. K. Rowling
5      harry potter and the sorcerer's stone (book 1)  J. K. Rowling
9   harry potter and the order of the phoenix (boo...  J. K. Rowling
13   harry potter and the chamber of secrets (book 2)  J. K. Rowling

                                          Image-URL-M  num_ratings  avg_rating
0   http://images.amazon.com/images/P/0439136350.0...          428    5.852804
3   http://images.amazon.com/images/P/0439139597.0...          387    5.824289
5   http://images.amazon.com/images/P/0590353403.0...          278    5.737410
9   http://images.amazon.com/images/P/043935806X.0...          347    5.501441
13  http://images.amazon.com/images/P/0439064872.0...          556    5.183453

In [21]:
print(merged_df.columns.tolist())

['Book-Title', 'num_ratings', 'avg_rating', 'ISBN', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L']

In [22]:
popular_df = merged_df.drop_duplicates('Book-Title')[
    ['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings', 'avg_rating']
]

In [23]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_rating
0,harry potter and the prisoner of azkaban (book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,harry potter and the goblet of fire (book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,harry potter and the sorcerer's stone (book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,harry potter and the order of the phoenix (boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,harry potter and the chamber of secrets (book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,the hobbit : the enchanting prelude to the lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,the fellowship of the ring (the lord of the ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,harry potter and the sorcerer's stone (harry p...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"the two towers (the lord of the rings, part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,to kill a mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,the da vinci code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,the five people you meet in heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,the catcher in the rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,the lovely bones: a novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,prodigal summer: a novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,the secret life of bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,stupid white men ...and other sorry excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"tuesdays with morrie: an old man, a young man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,the red tent (bestselling backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,the hitchhiker's guide to the galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,nickel and dimed: on (not) getting by in america,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,into the wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,girl with a pearl earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
120,outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
126,where the heart is (oprah's book club (paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
127,seabiscuit: an american legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
129,life of pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
133,the bean trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
136,"a child called \it\"": one child's courage to s...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
138,angela's ashes,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
140,good in bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
143,fast food nation: the dark side of the all-ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
144,american gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
146,skipping christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
152,left behind: a novel of the earth's last days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
154,"the golden compass (his dark materials, book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
162,the color purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
168,silence of the lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
171,about a boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
180,seven up (a stephanie plum novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
182,the alchemist: a fable about following your dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
184,hard eight : a stephanie plum novel (a stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
189,suzanne's diary for nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
193,lord of the flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
199,a prayer for owen meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
201,"the vampire lestat (vampire chronicles, book ii)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
202,white oleander : a novel (oprah's book club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

In [24]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

## Collaborative Filtering Based Recommender System

In [25]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
padhe_likhe_users = x[x].index

In [26]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]

In [27]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

famous_books

In [28]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [29]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [30]:
pt.fillna(0,inplace=True)

In [31]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity_scores = cosine_similarity(pt)

In [34]:
similarity_scores.shape

(706, 706)

In [36]:
def recommend(book_name):
    book_name = book_name.strip().lower()

    # Normalize pt index for matching
    normalized_titles = [title.strip().lower() for title in pt.index]

    if book_name not in normalized_titles:
        return f"❌ Book '{book_name}' not found in dataset."

    index = normalized_titles.index(book_name)
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x: x[1], reverse=True)[1:6]

    data = []
    for i in similar_items:
        title = pt.index[i[0]]
        temp_df = books[books['Book-Title'].str.strip().str.lower() == title.strip().lower()]
        
        if not temp_df.empty:
            item = [
                temp_df['Book-Title'].values[0],
                temp_df['Book-Author'].values[0],
                temp_df['Image-URL-M'].values[0]
            ]
            data.append(item)

    return data

In [37]:
recommend('1984')

[['animal farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["the handmaid's tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['brave new world',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['the vampire lestat (vampire chronicles, book ii)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['the hours : a novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg']]

In [38]:
recommend('1984')

[['animal farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["the handmaid's tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['brave new world',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['the vampire lestat (vampire chronicles, book ii)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['the hours : a novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg']]

In [39]:
pt.index[545]

"The Handmaid's Tale"

In [40]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [41]:
books.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,classical mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,clara callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,decision in normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,flu: the story of the great influenza pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,the mummies of urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,0449906736,flashpoints: promise and peril in a new world,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
271356,0525447644,from one to one hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,lily dale : the true story of the town that ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,republic (world's classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,a guided tour of rene descartes' meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [42]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import pandas as pd
import pickle

books = pd.read_csv("Books.csv")

# Reduce size
books = books.drop_duplicates('Book-Title').head(5000)

# Build content string
books['combined'] = (
    books['Book-Title'].fillna('') + ' ' +
    books['Book-Author'].fillna('') + ' ' +
    books['Publisher'].fillna('') + ' ' +
    books['Year-Of-Publication'].astype(str)
)

C:\Users\krish\AppData\Local\Temp\ipykernel_5736\2603438811.py:6: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [44]:
# TF-IDF and similarity
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(books['combined'])
content_similarity = linear_kernel(tfidf_matrix, tfidf_matrix)

# Save results
pickle.dump(content_similarity, open('content_similarity.pkl', 'wb'))
pickle.dump(books, open('books_content.pkl', 'wb'))  # optional: save reduced book list

In [45]:
num_rating_df['Book-Title'] = num_rating_df['Book-Title'].str.upper()

In [46]:
# Create a copy for content-based recommendations
books_content = books.drop_duplicates('Book-Title').copy()

# Assign genres to Book Titles
def assign_genre(title):
    title = title.lower()
    if "love" in title or "romance" in title:
        return "Romantic"
    elif "war" in title or "history" in title:
        return "Historical"
    elif "magic" in title or "dragon" in title or "fantasy" in title:
        return "Fantasy"
    elif "space" in title or "robot" in title or "alien" in title:
        return "Science Fiction"
    elif "murder" in title or "thriller" in title or "secret" in title:
        return "Thriller"
    else:
        return "Others"

books_content['Genre'] = books_content['Book-Title'].apply(assign_genre)

# ✅ Save this updated DataFrame
pickle.dump(books_content, open('books_content.pkl', 'wb'))